import { Inter } from "next/font/google";
import "./globals.css";
import Background from "@/components/ui/backGround";
import NavBar from "@/components/navbar/navbar";
import { Providers } from "./Providers";
import { Loader } from "@/components/ui/laoder/loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {/* //aplicar loader */}
        {/* <Loader />  */}
        <Providers>
          <Background />
          <NavBar />

          {children}
        </Providers>
      </body>
    </html>
  );
}
